### ISSUE TITLE
Bedrock Layer is not generated using Cave Biomes + Minecraft 1.18 Datapack

### ISSUE THREAD

**Issue by kalinzange** [kwpugh/mining_Dimensions#1]
Hi,

not sure what to describe better this issue but the title resumes everything. I have [Cave Biomes](https://www.curseforge.com/minecraft/mc-mods/cave-biomes) and the Minecraft 1.18 Datapack (Makes us go y -64) if we enter on the mining dimension (CobbleStone Portal) we don't have a bedrock layer. Not sure if this intentional or expected behaviour from your mod. Screenshot Below:

![image](https://user-images.githubusercontent.com/38161086/122659489-9158f280-d170-11eb-8a31-c5a697522723.png)

**Comment by kwpugh** [comment]
If you are using the CavesAndCliffsPreview data pack, you have to enable the option for worldgen in the Gobber config.

**Comment by kalinzange** [comment]
We are not using Gobber Mod. This is a Singleplayer World

**Comment by kwpugh** [comment]
BTW: mods that add dimensions for 1.17 are going to be designed for worlds with 1.17 world height, not 1.18 height.

**Comment by kwpugh** [comment]
Sorry, Mining Dimension.

**Comment by kalinzange** [comment]
> BTW: mods that add dimensions for 1.17 are going to be designed for worlds with 1.17 world height, not 1.18 height.

Ah.. Okay then!

My config for Mining Dimension only shows:

```
{
	/* 
	   
	   ***********************
	   Dimensions
	   ***********************
	*/
	"enableMining": true,
	"enableHunting": true,
	"enableCaving": true,
	"enableNethering": true
}
```

**Comment by kwpugh** [comment]
I'm confused, sorry.  Mining dim will not support 1.18 world height.

**Comment by kwpugh** [comment]
I was thinking about ore gen.

**Comment by kalinzange** [comment]
I see, no problem then! Once 1.18 is out do you have plans to have it supported or the mod updated?

**Comment by kwpugh** [comment]
When mods go to 1.18, they will support 1.18 features.  1.18 is due out in about 5 months.

**Comment by kalinzange** [comment]
> When mods go to 1.18, they will support 1.18 features. 1.18 does out in about 5 months.

I know 😄 Thanks for it!

**Comment by kwpugh** [comment]
Just be careful, I have talked to several other mod authors and there have been some bad issues using the 1.18 preview data pack with mods, crashes, and corrupted world.  It is not recommended for use with mods.

**Comment by kalinzange** [comment]
Oh thanks for the heads up, currently I'm just creating a modpack with the 1.18 preview to see how the cliffs look like, this is just for tests and see where it goes also my worlds are on creative for me to try out so, thank you 😄 I will probably delete it once I'm done with the tests

**Comment by kwpugh** [comment]
Best of luck.
