### ISSUE TITLE
Mining & Caving Portals don't work

### ISSUE THREAD

**Issue by ClaudiusMinimus** [kwpugh/mining_Dimensions#12]
I am working on a 1.18 pack and found the Mining & Caving Portals don't work. I then tried it in a fresh install with no other mods, except the Mining Dimensions and it still did not work.

Minecraft Version: 21w43a snapshot 1.18
Mining Dimensions Fabric: 1.18-21w43a-1.2.19
Fabric: 0.12.3

![2021-11-02_15 03 43](https://user-images.githubusercontent.com/17887664/139952879-b2532816-2a34-41b6-aba1-404d43adafc4.png)

**Comment by kwpugh** [comment]
Mining portal changed to deepslate, caving dim changed to tuff

**Comment by kwpugh** [comment]
Mentioned on webpage:

![Screen Shot 2021-11-02 at 4 22 15 PM](https://user-images.githubusercontent.com/8809210/139953586-dd84e840-55d3-4573-ae18-9a18146b3811.png)

**Comment by ClaudiusMinimus** [comment]
Thanks, that works great!
