### ISSUE TITLE
[1.18.1] Game does not load

### ISSUE THREAD

**Issue by ReiNAce** [kwpugh/mining_Dimensions#16]
I don't know why my Minecraft 1.17.1 doesn't load when I installed Mining Dimensions mod, maybe an incompatibility with The Aether mod but I am not sure. Can this incompatibility be fixed? Thanks.
Logs and Crash reports are as follows:

[latest.log](https://github.com/kwpugh/mining_Dimensions-1.17/files/7632317/latest.log)
[crash-2021-12-01_16.48.37-client.txt](https://github.com/kwpugh/mining_Dimensions-1.17/files/7632319/crash-2021-12-01_16.48.37-client.txt)

By the way, I am using Fabric Loader 0.12.5

**Comment by kwpugh** [comment]
I got a crash trying as well with 0.12.5.  Aether wants 0.12.6 or higher.  I installed 0.12.11 and no crash, worked fine.

**Comment by kwpugh** [comment]
Seems to be fixed with the loader update.
