### ISSUE TITLE
[1.17.1] Incompatibility between Iris, Sodium & CustomPortalsAPI

### ISSUE THREAD

**Issue by LucyusSama** [kwpugh/mining_Dimensions#17]
This mod is incompatible with Iris and Sodium

**Comment by kwpugh** [comment]
As are lots of others.  Unless you have something specific (like a crash report of errors from a log, not much I can go about it.

**Comment by LucyusSama** [comment]
when i light the flint, this is what happen
![image](https://user-images.githubusercontent.com/55464997/144913645-59fdf763-9654-45d8-84e5-defd1cb1cda8.png)
 this is the crash screen
 
![image](https://user-images.githubusercontent.com/55464997/144913870-6fc66ed7-eebb-43e9-a8d8-bed381f6b002.png)
when i try to re enter my save, this is the... portal...

**Comment by LucyusSama** [comment]
the crash log:
[crash-2021-12-06_16.54.19-client.txt](https://github.com/kwpugh/mining_Dimensions-1.17/files/7663246/crash-2021-12-06_16.54.19-client.txt)

**Comment by LucyusSama** [comment]
Oh and when i break the portal i get this portal (screen*)
![image](https://user-images.githubusercontent.com/55464997/144914415-ec4ebd3c-1254-41c6-bc78-acfc7cab768d.png)
Then when i get back, the portal frame is normal
![image](https://user-images.githubusercontent.com/55464997/144914532-c7769406-27a9-45de-8a1d-2bae613ca1ed.png)
like that

**Comment by kwpugh** [comment]
closing out to existing issue record.
