### ISSUE TITLE
[1.18.1] Conflict between BetterNether and Nethering Dimension

### ISSUE THREAD

**Issue by Houyami** [kwpugh/mining_Dimensions#18]
[crash-2021-12-11_01.09.39-server.txt](https://github.com/kwpugh/mining_Dimensions-1.17/files/7696602/crash-2021-12-11_01.09.39-server.txt)
Minecraft 1.18
Mod version: 1.2.35
Details: Crashes upon trying to enter the nethering dimension for the first time. Unknown as to how to resolve.

**Comment by kwpugh** [comment]
Please  test in 1.2.36 as a starting point for debugging.

**Comment by Sven-M-2018** [comment]
[crash-2022-01-04_14.35.16-server.txt](https://github.com/kwpugh/mining_Dimensions-1.17/files/7807954/crash-2022-01-04_14.35.16-server.txt)
[2022-01-04-1.log](https://github.com/kwpugh/mining_Dimensions-1.17/files/7807955/2022-01-04-1.log)

Minecraft: 1.18.1
Mod version: 1.2.38

I've been running into the same issue.

Some more information:
I've never been in the nethering dim, so minecraft is trying to build the dim.
I'm running immersive portals, so it's crashing when I try to light the portal.

**Comment by kwpugh** [comment]
Did you try without immersive portals to see if that is the problem

**Comment by kwpugh** [comment]
the  crash seems to happen with Better Nether,  perhaps it is generating a structure that is beyond the range on the tethering dimension.

**Comment by kwpugh** [comment]
In my test it crashed trying to create a better nether: nether city

**Comment by Sven-M-2018** [comment]
[crash-2022-01-04_15.22.00-server.txt](https://github.com/kwpugh/mining_Dimensions-1.17/files/7808212/crash-2022-01-04_15.22.00-server.txt)
[2022-01-04-5.log](https://github.com/kwpugh/mining_Dimensions-1.17/files/7808213/2022-01-04-5.log)

Disabling immersive portals does not help.

-----

Disabling BetterNether does help.

Shouldn't the nethering dim NOT use any nether mods?
Is it possible to solve this on your side?

**Comment by kwpugh** [comment]
The nethering dim is simply a datapack dim that uses the built-in vanilla nether type generator.  Mods that  tweak/adjust/replace the vanilla  nether generator might break the nethering dim (or any dim created by the vanilla generator).

**Comment by Sven-M-2018** [comment]
OK, so you can't access the "original vanilla generator" as long as the "BetterNether vanilla generator" is in place.
That's bad, but I understand the problem.

Do you see any chance to create compatibility with BetterNether?

**Comment by kwpugh** [comment]
Try deleting the tethering dim and try to re-create.

**Comment by Sven-M-2018** [comment]
> Try deleting the tethering dim and try to re-create.

I guess you meant the nethering dim? I just created this dim after I disabled BetterNether?!
I can now visit this dim, but I guess when I re-enable BetterNether I might run into troubles when new chunks are generated...

So I guess my best try would be to pregen quite a few chunks before re-enabling BetterNether - as long as you don't tell me there's an easy compatibility fix.

**Comment by kwpugh** [comment]
there is not, Better Nether replaces the vanilla nether generator.  To get around the problem, I would have to create my own generator for nether types, which I have no desire to do.  Better Nether is still in beta and quite buggy, so perhaps future version with work the situation out.  In 1.17.1, both mods were able to work together.

**Comment by Sven-M-2018** [comment]
OK, and thanks for your quick help.

**Comment by Sven-M-2018** [comment]
Fixed with the latest BCLib version.

**Comment by kwpugh** [comment]
Wonderful.  Thank you.

**Comment by kwpugh** [comment]
This one: bclib-1.2.5-1.18/1.18.1

**Comment by kwpugh** [comment]
Tested out, looks good.  Thanks again.
