### ISSUE TITLE
[1.18.1] Mining dimension appears to only generate desert

### ISSUE THREAD

**Issue by GarethPW** [kwpugh/mining_Dimensions#19]
As defined in [`src/main/resources/data/mining_dims/dimension/mining_dim.json`](https://github.com/kwpugh/mining_Dimensions-1.17/blob/1.18.1/src/main/resources/data/mining_dims/dimension/mining_dim.json), plains should be generated too. However, I have been unable to locate any – not via commands or by manually searching. If I'm incorrect in thinking this is not the intended behaviour, then I apologise.

**Comment by kwpugh** [comment]
It is supposed to be both desert and plains, I will look into this.  Might be an issue with the new biomes api and data packs.

**Comment by kwpugh** [comment]
Fixed in v1.2.40
