### ISSUE TITLE
Open void in the mining dimesion

### ISSUE THREAD

**Issue by LMSparrow** [kwpugh/mining_Dimensions#2]
I'm using the 1.18 generation datapack for 1.17 while using this mod and I come across a pocket of void where the rest of the cave would be.
![2021-07-21_16 25 01](https://user-images.githubusercontent.com/87787333/126572534-b84bd689-4738-4a81-ba5a-6df0dd47d7ae.png)

**Comment by kwpugh** [comment]
Yep, 1.17 mods are designed for 1.17 not 1.18.

**Comment by YuRaNnNzZZ** [comment]
https://feedback.minecraft.net/hc/en-us/articles/4402614709389-Caves-Cliffs-Prototype-Data-Pack-for-Minecraft-Java-Edition
This is clearly a 1.17 datapack, intended to run in 1.17.

**Comment by kwpugh** [comment]
it changes world height which is not currently supported as a general standard.  I will be supporting the new world height when Mojang releases it with 1.18.

**Comment by YuRaNnNzZZ** [comment]
it's okay, a simple datapack with edited world heights seem to fix that
![](https://user-images.githubusercontent.com/5104603/126574948-6943f88d-9e32-4d13-a70e-4ed5ac1a3283.png)

**Comment by kwpugh** [comment]
very good.  Mods cannot access the new world height, because it is not part of the Fabric API.  

Enjoy.

**Comment by LMSparrow** [comment]
You could just force a layer of bedrock at y 0 like in a superflat world

**Comment by kwpugh** [comment]
I'm fine waiting until I see how Mojang implements things in 1.18
