### ISSUE TITLE
[1.18.1] Biome decoration I java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0

### ISSUE THREAD

**Issue by TheButterbrotMan** [kwpugh/mining_Dimensions#20]
When trying to join the mining dimension

https://pastebin.com/5MSjv83V

**Comment by kwpugh** [comment]
Looks like joining the nethering dim, not mining dim.

**Comment by kwpugh** [comment]
Closing to existing open issue on BetterNether issues.

https://github.com/kwpugh/mining_Dimensions-1.17/issues/18
