### ISSUE TITLE
[1.18.1] Nethering Dimension won't open

### ISSUE THREAD

**Issue by jacquesco07** [kwpugh/mining_Dimensions#21]
As stated. I've used basalt and smooth basalt but when I try to light it with a flint and steel, the portal does not open.

**Comment by kwpugh** [comment]
Modpack?  Server?

**Comment by jacquesco07** [comment]
> Modpack? Server?

Added it to my Euphoric Curiosity Modpack Server. Other dimensions work just fine

**Comment by kwpugh** [comment]
I just tested out on my server and it lit fine.  Are you using any other portal mods like Immersive Portals or such?

**Comment by jacquesco07** [comment]
No, nothing else. I think it's weird how the other portals, (mining, climbing, hunting, caving) work, but not the nethering.

**Comment by kwpugh** [comment]
you double checked it wasn't disabled for some reason in the config?

**Comment by jacquesco07** [comment]
Oh, yep. There it is. It was disabled. Thanks! lol

**Comment by kwpugh** [comment]
Enjoy
