### ISSUE TITLE
[1.18.1] FerriteCore doesn't like something that MD is doing

### ISSUE THREAD

**Issue by Desempregago** [kwpugh/mining_Dimensions#24]
[Crash Report](https://pastebin.com/6LacyTDj)

Mining Dimensions: 1.3.0
FerriteCore: 4.1.0

Happened after using a caving portable teleporter

**Comment by kwpugh** [comment]
I  just tried this on my side with FerriteCore and it doesn't crash.  are you  running this single player or server?

**Comment by Desempregago** [comment]
Singleplayer, but disabling a config line related to threading in ferritecore fixed it

**Comment by kwpugh** [comment]
ok, good to know.
