### ISSUE TITLE
[1.18.1] TerraBlender blocking JSON dimension creation/usage

### ISSUE THREAD

**Issue by Karim246** [kwpugh/mining_Dimensions#26]
None of the teleporters work and eve when i use a command it tells me that the mining dimension doesnt exis
![Minecraft Screenshot 2022 02 14 - 13 53 46 84](https://user-images.githubusercontent.com/99122906/153877276-a2a86980-ebd5-4bb4-8e03-bf5853ea4de8.png)
t

**Comment by Karim246** [comment]
I also cannot light or make any of the portals but maybe thats my fault. Eg it says for caving dim i need a tuff portal and i built it but it looks nothing like your portal the one with the coloured bricks.

**Comment by kwpugh** [comment]
Are you using TerraBlender?

**Comment by kwpugh** [comment]
v1.3.0+ now uses the portal blocks for the portals.

**Comment by Karim246** [comment]
Yeah im using terrablender.
But just yesterday it was working fine with the teleporters then today i boot it up and it suddenly wont do anyhting.
Should i remove terrablender?

**Comment by kwpugh** [comment]
https://github.com/Glitchfiend/TerraBlender/issues/38

There is an issue that TerraBlender breaks JSON dimensions

**Comment by Karim246** [comment]
Oh ok ill remove it and try i dont even think im using any biome mods

**Comment by Karim246** [comment]
Yes! It works now thank you

**Comment by kwpugh** [comment]
I'll leave this open until TerraBlender is fixed.

**Comment by Karim246** [comment]
Ok

**Comment by kwpugh** [comment]
Fixed by TerraBlender
