### ISSUE TITLE
Villages in The Hunting Dimension?

### ISSUE THREAD

**Issue by KingMushroomBoy** [kwpugh/mining_Dimensions#28]
Where are they? I loved them so much and it was fun talking to villagers or taking over the houses for protection. I played the 1.18.1 version and they are nowhere :(
I thought this was intentional so I am posting this here because it might just be a bug that they are not spawning.

**Comment by KingMushroomBoy** [comment]
So boring without them.

**Comment by kwpugh** [comment]
not intenntional.  There should be villages.  Are you using 1.18.2?

**Comment by kwpugh** [comment]
Looks like they moved the structures that go into biomes into separate JSON and now are tagged.

I'll take a look at adding them back.

**Comment by KingMushroomBoy** [comment]
Oh I am on 1.18.1 not 1.18.2

**Comment by kwpugh** [comment]
I'm  not sure where it changed.  If I can fix it, it will be in 1.19.

**Comment by kwpugh** [comment]
The village of eternal darkness returns in 1.18.2 and 1.19

![2022-06-05_12 04 30](https://user-images.githubusercontent.com/8809210/172061931-4370a9cc-50b6-4066-bcf8-52b0818dc27b.png)

**Comment by KingMushroomBoy** [comment]
Thanks!
They also added the new 1.18.2 version to the mod so that was perfect timing! Happy ending.
