### ISSUE TITLE
[1.19] Cave dimension should have clouds disabled

### ISSUE THREAD

**Issue by NobleDraconian** [kwpugh/mining_Dimensions#29]
As of `v1.3.7`, the "cave" dimension does not have clouds disabled! To my knowledge this is a pretty simple fix in the datapack's json. This is obviously funny to look at and should be fixed.
![image](https://user-images.githubusercontent.com/26460940/174526817-43c13fa0-b2cc-4701-9146-3ca78a398125.png)

**Comment by kwpugh** [comment]
In latest release, no more clouds, but a bit of eerie fog.

**Comment by NobleDraconian** [comment]
@kwpugh Could this fix be backported to 1.18? Most of the mods I use aren't available on 1.19 unfortunately, so my personal modpack is on 1.18.

**Comment by kwpugh** [comment]
since  it  is a one-line change I  will update 1.18.2

**Comment by NobleDraconian** [comment]
Awesome, thank you! 😄
