### ISSUE TITLE
Odd Exit/Entry On Dimension Shift

### ISSUE THREAD

**Issue by Kronon-Conspirator** [kwpugh/mining_Dimensions#3]
when changing dimensions (Especially dangerous on The Nether Mining dim), the entry has a second exit point (its consistent) and sometimes randomly chooses where to spit the user out. this also happens when going back to the overworld. Either it Generates a new portal elsewhere, spits you out at random or on rare occasions sends you back to the original portal. the other exit points have a consistent coords.

tested on v1.17.1-1.1.9

**Comment by kwpugh** [comment]
This is an existing issue with the custom portals api that I use for the mod.  

https://github.com/kyrptonaught/customportalapi/issues/26

Closing to that. open issue.  I would recommend using the portable teleporters personally, until it is fixed.
