### ISSUE TITLE
[Suggestion] Disabling dimensions

### ISSUE THREAD

**Issue by Traktool** [kwpugh/mining_Dimensions#30]
Hi !

I suggest adding a way to disable certain dimensions
Something like :
```
enableMiningDim: true
enableClimbingDim: true
enableHuntingDim: true
enableCavingDim: true
enableNetheringDim: true
```

**Comment by kwpugh** [comment]
Changes in how registry work in 1.18+ no longer make disabling via config viable or recommended.

You can disable portal block recipes via data packs or KubeJS for dims you do not want.
