### ISSUE TITLE
Exploding Beds :|

### ISSUE THREAD

**Issue by XenoTheStrange** [kwpugh/mining_Dimensions#31]
I didn't know that beds would explode in the mining dimension. I right clicked on a villager who was sleeping, intending to trade, but my click went through him and the entire building exploded. The villager died and I lost some items.
Now I know that this is a thing... can a dude get some warning? My poor house and villager.

Not exactly an issue I know, but feels bad :/
![image](https://user-images.githubusercontent.com/48196283/180658448-c1e2a3b5-ef93-4c00-ab48-5b992f84b37e.png)

**Comment by kwpugh** [comment]
I can put a comment on the CF page about that.  

It is pretty much a given that you get exploding beds in dims except for the Overworld.  Ever try sleeping in the Nether or the End?

Sorry you lost stuff though.

**Comment by kwpugh** [comment]
<img width="1282" alt="Screen Shot 2022-07-24 at 12 27 52 PM" src="https://user-images.githubusercontent.com/8809210/180658995-19963d60-dbb8-4407-a344-d442ce0e0f46.png">
