### ISSUE TITLE
[1.19.2] Crash when Super Block World is used

### ISSUE THREAD

**Issue by ghost** [kwpugh/mining_Dimensions#32]
Crashes with [Super Block World](https://www.curseforge.com/minecraft/mc-mods/super-block-world)
do to Super Block World useing a newer ver of custom portal api
and it does not work with mining dimensions
so um update your custom portal api or someing

**Comment by kwpugh** [comment]
Please post t he crash support.

**Comment by kwpugh** [comment]
Updated Mining Dims mod to latest CustomPortal API, seems to load fine with Super Block World.
