### ISSUE TITLE
Latest version targets newer than available fabric loader

### ISSUE THREAD

**Issue by nekoyoubi** [kwpugh/mining_Dimensions#33]
The latest version, `MiningDimensions_Fabric-1.19.2-1.4.27.jar`, is targeting a version of the Fabric loader (0.14.10) that is apparently ahead of the MC 1.19.2 Fabric that CurseForge is pushing (0.14.9). I also assume that I'm not behind the times because my hundreds of other mods all play nice with the latest Fabric, and there was a new push today that still causes the following exception with MiningDimensions turned on.

```
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Fabric Loader' (fabricloader) 0.14.9 with version 0.14.10 or later.
Unmet dependency listing:
	 - Mod 'Mining Dimensions' (mining_dims) 1.4.27 requires version 0.14.10 or later of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.14.9!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by kwpugh** [comment]
I have heard that the oversold launcher did not update to have 0.14.10 of fabric.  Just use the previous version of Mining Dims until your launcher supports the latest.
