### ISSUE TITLE
[1.20] Nethering dimension without amplified nether

### ISSUE THREAD

**Issue by matejbrezovic** [kwpugh/mining_Dimensions#34]
Hello, is it possible to make it so that nethering dimension isn't affected by amplified nether datapack? Primarily because of making farms in nether. Because amplified nether goes all the way up to y=255 there is no room to build on the nether roof. So if nethering dimension is unaffected you could build farms there. That would make it possible to have one modded nether looking beautiful with  amplified nether, or some other mod, while still having the vanilla nether for making farms.

**Comment by kwpugh** [comment]
I'm not sure if I can.  I will investigate.

**Comment by kwpugh** [comment]
This is not something I can reasonably change.  My Nethering Dim is a copy of vanilla's nether dim world type.  amplified nether OVERWRITES the vanilla nether setting, so my dim will be based on that instead.  I have no desire to create a nether-like dim from scratch, with all the builtin support that vanilla already provides.  sorry.
