### ISSUE TITLE
[1.19.2] Teleporter takes you to a copy of the overworld?

### ISSUE THREAD

**Issue by TheGag96** [kwpugh/mining_Dimensions#36]
We used a Mining Teleporter, and instead of taking what is described on the mod page as the Mining Dimension, it takes you to what looks to be a copy of the overworld. Strangely, when a copy of an overworld waystone from the "Fabric Waystones" mod was used in the Mining Dimension, it modifies the original such that no other players who had access to the waystone prior can see it in their list anymore.

**Comment by kwpugh** [comment]
The mining dim is a copy of the overworld with only two biomes, as described on the CurseForge page.
