### ISSUE TITLE
portal lighter

### ISSUE THREAD

**Issue by orangetaker** [kwpugh/mining_Dimensions#37]
the portal lighter doesn't light the portal and I cant figure out how to get the return enchant 1.19.3

**Comment by kwpugh** [comment]
Make sure the portals are not disabled in the config

**Comment by Rogenar** [comment]
Although the portals are active, they cannot be illuminated with a lighter and when I type in the search section, the lighter does not appear, but it can be produced. Versiyon Fabric-1.19.3-rc1-1.5.7

**Comment by orneo1212** [comment]
Where can i get portal lighter? No recipe for it

**Comment by CerezaKitty** [comment]
There's currently no portal lighter in the mod for some reason?

**Comment by orneo1212** [comment]
Its craftable with Diamond + flint shapeless. But don't work on portal 2x3 with dim block

**Comment by kwpugh** [comment]
Portals are not available in 1.19.3, use portable teleporters to get to dims for now.

**Comment by orneo1212** [comment]
when portals will be added in 1.9.3?

niedz., 29 sty 2023, 18:10 użytkownik Kevin Pugh ***@***.***>
napisał:

**Comment by CerezaKitty** [comment]
Well there's nothing in the config folder that says anythting about the portal lighter, I managed to find how to make one, a Diamond and Flint but It seems you can't light the portal otherwise

**Comment by CerezaKitty** [comment]
> Portals are not available in 1.19.3, use portable teleporters to get to dims for now.

What's the point on having the portals then? I wanted to place them around the base to make it look cool like a portals room

**Comment by kwpugh** [comment]
The custom portals api had not updated before I left for holiday.  When I get back to modding in May, I will look to add that back in.

**Comment by kwpugh** [comment]
portals are not supported in 1.19.3 and 1.19.4.   They returned in 1.20.1 and 1.20.4.
