### ISSUE TITLE
[1.17.1] CustomPortalsAPI conflict with Atlantis mod

### ISSUE THREAD

**Issue by deftesthawk** [kwpugh/mining_Dimensions#4]
when I have this installed with the Atlantis mod the game crashes on start up

fabric
Minecraft 1.17.1

**Comment by kwpugh** [comment]
crash report?

**Comment by deftesthawk** [comment]
[crash-2021-08-11_21.08.48-client.txt](https://github.com/kwpugh/mining_Dimensions-1.17/files/6971125/crash-2021-08-11_21.08.48-client.txt)

**Comment by kwpugh** [comment]
the crash explicitly calls on AtlantsisClearPortalBlock, I do not see anything particular to my mod.   The only connection is that we are both using the embedded CustomPortalsAPI.

I see that you opened an issue with the other other.  I think the author needs to pursue this on their end.

https://github.com/Exploding-Creeper/atlantis/issues/36

**Comment by deftesthawk** [comment]
Okay, thanks for the info :)

**Comment by Mysticpasta1** [comment]
This crash was unknown to me I try to fix it but seems like it is the api itself --> https://github.com/kyrptonaught/customportalapi

**Comment by kwpugh** [comment]
I'm no longer going to track this one.
