### ISSUE TITLE
Feature Suggestion: Ability to disable portable teleporters and the enchantment assiociated

### ISSUE THREAD

**Issue by Dutchsnake5** [kwpugh/mining_Dimensions#41]
I was wondering if it would be a viable option to allow the config to disable the portable teleporter, as well as the associated enchantments. This would be nice for modpacks that wanna keep it relatively vanilla with the portals, and I think it would also just be a nice to have feature

**Comment by kwpugh** [comment]
As a rule, it is not consider good practice in mod config to disable items.  You can remove the portable teleporters recipes for you modpack and achieve the same result.
