### ISSUE TITLE
[Fabric 1.19.2] Using Returning Enchantment resets level

### ISSUE THREAD

**Issue by Sekyno** [kwpugh/mining_Dimensions#43]
Using a teleporter with Returning enchantment on it to return to bed resets player's level to 0
Please check out the attached video

https://github.com/kwpugh/mining_Dimensions/assets/140377685/ef01015b-b3bf-45af-955b-bf1db078991e

**Comment by kwpugh** [comment]
This is a known bug relating to xp and crossing dimensions.   your xp is still there, it is not being displayed.  

I assume when you relax the xp comes back?

**Comment by kwpugh** [comment]
Ok, I figured out how to fix this. I will publish updates.
