### ISSUE TITLE
Portals won't light 1.19.2 Fabric

### ISSUE THREAD

**Issue by AzrouStone** [kwpugh/mining_Dimensions#44]
Can portals light next to each other like in your thumbnail or are they unable to? Because I made one working portal and can't light the other two beside it.

**Comment by kwpugh** [comment]
IS this want you mean?

![Screenshot 2024-05-07 at 8 47 59 PM](https://github.com/kwpugh/mining_Dimensions/assets/8809210/fa55447f-4301-4543-b306-2a1d1a616a9b)

I hadn't played 1.19.2 in a while so I fired it up.   I am able to place the portals next to each other and light them.
