### ISSUE TITLE
minecraft 1.17.1 fabric

### ISSUE THREAD

**Issue by quentfr21** [kwpugh/mining_Dimensions#5]
hello

when you pass a portal and then return to it you sometime spawn far away  from the created portal

thanks in advance

i run it on a dedicated server

**Comment by kwpugh** [comment]
Know issue.

**Comment by kwpugh** [comment]
Tracking via this issue with the custom portals API

**Comment by kwpugh** [comment]
https://github.com/kyrptonaught/customportalapi/issues/26
