### ISSUE TITLE
could cause "timed out" error on server

### ISSUE THREAD

**Issue by quentfr21** [kwpugh/mining_Dimensions#6]
hello

i run it on server

after some use of dimension if you stay in a mining dimension for a long time you get a timed out error when you go back

on my server i even can't connect because of this, the only way is restarting the server and after that it work 

if the server run without client for about 2 - 3 hours you can connect due to timed out after logged in

thankd in advance

after removing it no more pb 

edit: it's may be related to literally chunk loader because i try to put one in the dimension but it's not able to load modded dimension maybe it break something after removing restart and re installing mods it's look like ok for now i will let you know if it's happend again

edit 2 : happend again that may be linked to "Additional Enchanted Miner" mod that i use to mine and that the only thing a made in dimension

**Comment by kwpugh** [comment]
the mining dimension is a data pack vanilla managed dimension.  any time outs or such are going to be related to vanilla and/or other mods.   Nothing I can control about it, since the dims are entirely JSON based.
