### ISSUE TITLE
[1.17.1] Iron Golem collide with customportalapi:customportalblock 

### ISSUE THREAD

**Issue by manaheti1** [kwpugh/mining_Dimensions#9]
Well I set up are Cobble Stone Portal at my village and go mining and then Minecraft shutdown, you can get full log here: https://pastebin.com/RmZid53s
These are noticeable part :
-- Entity being loaded --
Details:
	Entity Type: minecraft:iron_golem (net.minecraft.class_1439)
	Entity ID: 3528
	Entity Name: Iron Golem
	Entity's Exact location: 185.67, 69.00, 196.03
	Entity's Block location: World: (185,69,196), Section: (at 9,5,4 in 11,4,12; chunk contains blocks 176,0,192 to 191,255,207), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: -0.05, 0.00, -0.00
	Entity's Passengers: []
	Entity's Vehicle: null

-- Block being collided with --
Details:
	Block: Block{customportalapi:customportalblock}[axis=z]
	Block location: World: (184,69,195), Section: (at 8,5,3 in 11,4,12; chunk contains blocks 176,-64,192 to 191,319,207), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)

-- Entity being checked for collision --
Details:
	Entity Type: minecraft:iron_golem (net.minecraft.class_1439)
	Entity ID: 3151
	Entity Name: Iron Golem
	Entity's Exact location: 185.67, 69.00, 196.03
	Entity's Block location: World: (185,69,196), Section: (at 9,5,4 in 11,4,12; chunk contains blocks 176,-64,192 to 191,319,207), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Entity's Momentum: -0.05, -0.00, -0.00
	Entity's Passengers: []
	Entity's Vehicle: null

-- Entity being ticked --
Details:
	Entity Type: minecraft:iron_golem (net.minecraft.class_1439)
	Entity ID: 3151
	Entity Name: Iron Golem
	Entity's Exact location: 185.67, 69.00, 196.03
	Entity's Block location: World: (185,69,196), Section: (at 9,5,4 in 11,4,12; chunk contains blocks 176,-64,192 to 191,319,207), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Entity's Momentum: -0.05, -0.00, -0.00
	Entity's Passengers: []
	Entity's Vehicle: null

-- Affected level --
Details:
	All players: 1 total; [class_3222['Nghia'/109, l='ServerLevel[SuperX]', x=131.48, y=42.00, z=220.71]]
	Chunk stats: 2682
	Level dimension: minecraft:overworld
	Level spawn location: World: (-112,70,48), Section: (at 0,6,0 in -7,4,3; chunk contains blocks -112,-64,48 to -97,319,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 76005 game time, 107793 day time
	Level name: SuperX
	Level game mode: Game mode: survival (ID 0). Hardcore: true. Cheats: false
	Level weather: Rain time: 94747 (now: false), thunder time: 90535 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil

**Comment by kwpugh** [comment]
The latest version of the mod has a brand new version of the customportalsapi.  Let me know if this still happens.

**Comment by kwpugh** [comment]
I played with this a few times in my test world and it doesn't seem to happen any more.
